name: Go Deploy

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDS }}
    
    - name: Build app in ACR and push
      run: |
        echo "Building API-USER-GO image..."
        az acr build --image "devopsoh/api-trips:${{ github.sha }}" --registry openhackx6e34ru4acr --file Dockerfile .
        
  deploy:
    if: success()    # Deploy only when build was successful
    needs: build     # Wait for deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDS }}

      - name: Deploy to Azure WebApp
        uses: Azure/webapps-deploy@v2
        with:
          app-name: openhackx6e34ru4trips
          slot-name: production
          images: "openhackx6e34ru4acr.azurecr.io/devopsoh/api-user-trips:${{ github.sha }}"
